from agents.frameworks.chat_llm import ChatLLM
from agents.guesser.goal_based_with_simple_prompt.program import simple_prompt_template

class SimpleGuesser:
    """A simple guesser agent for the 20 Questions game.

    Attributes:
        name (str): The name of the guesser agent.
        logger (Logger): The logger instance to log information and debug messages.
        llm (ChatLLM): The language model instance used for generating guesses based on input.
    """

    def __init__(self, logger, name):
        """Initialize the guesser agent.

        Args:
            logger (Logger): The logger instance for logging information and debugging.
            name (str): The name to be used for the guesser agent.
        """
        self.name = name
        self.logger = logger
        self.logger.info(f"Initializing {self.name} with prompt")
        # Instantiate the language model for the guesser with a specific prompt template
        self.llm = ChatLLM(logger=logger, prompt=simple_prompt_template.format(name=name))

    async def make_guess(self, message):
        """Make a guess based on the message from the host agent.

        Args:
            message (str): The input message from the host agent used to make a guess.

        Returns:
            str: The response containing the guess generated by guesser agent.
        """
        # Get the response from the language model based on the input message
        response = await self.llm.async_get_response_to_input(message)
        self.logger.info(f"Guesser responded with: {response}")
        return response